INSERT INTO users (user_id, name, email, cpf, password) VALUES
(1, 'Alisson Rodrigues', 'alisson@gmail.com', '12345678901', '$2b$10$4u1s.HiYa7VLM0Pjini4eeIvvAt3aUbOhortBkS3VI5mqreoNye2O');

INSERT INTO payment_method (name) VALUES
('Cartão de Crédito'),
('Cartão de Débito'),
('Pix'),
('Boleto Bancário'),
('Transferência Bancária'),
('Carnê'),
('Apple Pay'),
('Google Pay'),
('Dinheiro');

INSERT INTO bank_account (name, user_id) VALUES
('Carteira', 1);

INSERT INTO category (name, color, icon, operation, user_id) VALUES
('Moradia', '#ef4444', 'home', 'EXPENSE', 1),
('Transporte', '#f97316', 'directions_car', 'EXPENSE', 1),
('Alimentação', '#f59e0b', 'restaurant', 'EXPENSE', 1),
('Saúde', '#eab308', 'health_and_safety', 'EXPENSE', 1),
('Educação', '#84cc16', 'school', 'EXPENSE', 1),
('Lazer', '#22c55e', 'sports_esports', 'EXPENSE', 1),
('Roupas e Acessórios', '#10b981', 'checkroom', 'EXPENSE', 1),
('Eletrônicos', '#14b8a6', 'devices', 'EXPENSE', 1),
('Presentes e Doações', '#06b6d4', 'card_giftcard', 'EXPENSE', 1),
('Pets', '#0ea5e9', 'pets', 'EXPENSE', 1),
('Beleza e Cuidados Pessoais', '#3b82f6', 'spa', 'EXPENSE', 1),
('Emergências e Despesas Não Planejadas', '#6366f1', 'warning', 'EXPENSE', 1),
('Viagens', '#8b5cf6', 'flight', 'EXPENSE', 1),
('Assinaturas', '#a855f7', 'subscriptions', 'EXPENSE', 1),
('Serviços', '#d946ef', 'handyman', 'EXPENSE', 1),
('Entretenimento', '#ec4899', 'theaters', 'EXPENSE', 1),
('Diversos', '#f43f5e', 'category', 'EXPENSE', 1),
('Investimentos', '#ef4444', 'trending_up', 'EXPENSE', 1),
('Salário', '#f97316', 'attach_money', 'INCOME', 1),
('Empréstimos', '#f59e0b', 'account_balance', 'INCOME', 1),
('Rendimentos', '#eab308', 'savings', 'INCOME', 1),
('Outros', '#84cc16', 'more_horiz', 'INCOME', 1);

INSERT INTO issuers (name, logo_url, key_word, popularity, color, institution_type) VALUES
('Outros', 'public/issuers/other.png', 'other', 1, 'cc-other', 'ALL'),
('Nubank', 'public/issuers/nubank.png', 'nubank', 1, 'cc-nubank', 'ALL'),
('Banco Inter', 'public/issuers/intermedium.png', 'intermedium', 1, 'cc-inter', 'ALL'),
('Banco do Brasil', 'public/issuers/bb.png', 'bb', 1, 'cc-bb', 'ALL'),
('Bradesco', 'public/issuers/bradesco.png', 'bradesco', 1, 'cc-bradesco', 'ALL'),
('Caixa', 'public/issuers/caixa.png', 'caixa', 1, 'cc-caixa', 'ALL'),
('Hipercard', 'public/issuers/hipercard.png', 'hipercard', 1, 'cc-hipercard', 'BANK_ACCOUNT'),
('Itaú', 'public/issuers/itau.png', 'itau', 1, 'cc-itau', 'ALL'),
('Santander', 'public/issuers/santander.png', 'santander', 1, 'cc-santander', 'ALL'),
('Iti', 'public/issuers/iti.png', 'iti', 2, 'cc-iti', 'BANK_ACCOUNT'),
('Mercadopago', 'public/issuers/mercadopago.png', 'mercadopago', 2, 'cc-mercadopago', 'BANK_ACCOUNT'),
('PagBank', 'public/issuers/pagbank.png', 'pagbank', 2, 'cc-pagbank', 'ALL'),
('Pagseguro', 'public/issuers/pagseguro.png', 'pagseguro', 2, 'cc-pagseguro', 'ALL'),
('Paypal', 'public/issuers/paypal.png', 'paypal', 2, 'cc-paypal', 'BANK_ACCOUNT'),
('PicPay', 'public/issuers/picpay.png', 'picpay', 2, 'cc-picpay', 'ALL'),
('American Express', 'public/issuers/amex.png', 'amex', 2, 'cc-amex', 'BANK_ACCOUNT'),
('Mastercard', 'public/issuers/mastercard.png', 'mastercard', 2, 'cc-mastercard', 'BANK_ACCOUNT'),
('Visa', 'public/issuers/visa.png', 'visa', 2, 'cc-visa', 'BANK_ACCOUNT'),
('Diners', 'public/issuers/diners.png', 'diners', 2, 'cc-diners', 'BANK_ACCOUNT'),
('Elo', 'public/issuers/elo.png', 'elo', 2, 'cc-elo', 'BANK_ACCOUNT'),
('BTG Pactual', 'public/issuers/btgpactual.png', 'btgpactual', 2, 'cc-btg', 'BANK_ACCOUNT'),
('Banco PAN', 'public/issuers/pan.png', 'pan', 2, 'cc-pan', 'ALL'),
('Neon', 'public/issuers/neon.png', 'neon', 2, 'cc-neon', 'ALL'),
('Next', 'public/issuers/next.png', 'next', 2, 'cc-next', 'ALL'),
('C6 Bank', 'public/issuers/c6bank.png', 'c6bank', 2, 'cc-c6bank', 'ALL'),
('Agibank', 'public/issuers/agibank.png', 'agibank', 2, 'cc-agibank', 'ALL'),
('Digio', 'public/issuers/digio.png', 'digio', 2, 'cc-digio', 'BANK_ACCOUNT'),
('Recargapay', 'public/issuers/recargapay.png', 'recargapay', 2, 'cc-recargapay', 'BANK_ACCOUNT'),
('Rico', 'public/issuers/rico.png', 'rico', 2, 'cc-rico', 'BANK_ACCOUNT'),
('Safra', 'public/issuers/safra.png', 'safra', 2, 'cc-safra', 'ALL'),
('Sicoob', 'public/issuers/sicoob.png', 'sicoob', 2, 'cc-sicoob', 'ALL'),
('Sicredi', 'public/issuers/sicredi.png', 'sicredi', 2, 'cc-sicredi', 'ALL'),
('Sodexo', 'public/issuers/sodexo.png', 'sodexo', 2, 'cc-sodexo', 'ALL'),
('Sofisa direto', 'public/issuers/sofisadireto.png', 'sofisadireto', 2, 'cc-sofisa', 'ALL'),
('Xp Investimentos', 'public/issuers/xp.png', 'xp', 2, 'cc-xp', 'BANK_ACCOUNT'),
('alelo', 'public/issuers/alelo.png', 'alelo', 2, 'cc-alelo', 'BANK_ACCOUNT'),
('Flash', 'public/issuers/flash.png', 'flash', 2, 'cc-flash', 'BANK_ACCOUNT'),
('Will', 'public/issuers/willbank.png', 'willbank', 2, 'cc-will', 'ALL'),
('Ame Digital', 'public/issuers/ame.png', 'ame', 3, 'cc-amedigital', 'BANK_ACCOUNT'),
('BMG', 'public/issuers/bmg.png', 'bmg', 3, 'cc-bmg', 'ALL'),
('BRB', 'public/issuers/brb.png', 'brb', 3, 'cc-brb', 'ALL'),
('BRDE', 'public/issuers/brde.png', 'brde', 3, 'cc-brde', 'ALL'),
('BS2', 'public/issuers/bs2.png', 'bs2', 3, 'cc-bs2', 'ALL'),
('Banco da Amazonia', 'public/issuers/amazonia.png', 'amazonia', 3, 'cc-amazonia', 'ALL'),
('Banco Cacique', 'public/issuers/cacique.png', 'cacique', 3, 'cc-cacique', 'ALL'),
('Banco Votorantim', 'public/issuers/votorantim.png', 'votorantim', 3, 'cc-votorantim', 'ALL'),
('Banco do Nordeste', 'public/issuers/nordeste.png', 'nordeste', 3, 'cc-nordeste', 'ALL'),
('Banese', 'public/issuers/banese.png', 'banese', 3, 'cc-banese', 'ALL'),
('Banestes', 'public/issuers/banestes.png', 'banestes', 3, 'cc-banestes', 'ALL'),
('Banif', 'public/issuers/banif.png', 'banif', 3, 'cc-banif', 'ALL'),
('Banpara', 'public/issuers/banpara.png', 'banpara', 3, 'cc-banpara', 'ALL'),
('Banrisul', 'public/issuers/banrisul.png', 'banrisul', 3, 'cc-banrisul', 'ALL'),
('Bbm', 'public/issuers/bbm.png', 'bbm', 3, 'cc-bbm', 'ALL'),
('Cetelem', 'public/issuers/cetelem.png', 'cetelem', 3, 'cc-cetelem', 'ALL'),
('Citibank', 'public/issuers/citibank.png', 'citibank', 3, 'cc-citibank', 'ALL'),
('Cruzeirodosul', 'public/issuers/cruzeirodosul.png', 'cruzeirodosul', 3, 'cc-cruzeirodosul', 'ALL'),
('Digi+', 'public/issuers/digiplus.png', 'digiplus', 3, 'cc-digiplus', 'ALL');
